export const languages = [
  { label: "C", value: "c" },
  { label: "C++", value: "cpp" },
  { label: "Java", value: "java" },
  { label: "JavaScript", value: "javascript" },
  { label: "Python", value: "python" },
  { label: "Ruby", value: "ruby" },
  { label: "Go", value: "go" },
  { label: "Rust", value: "rust" },
  { label: "PHP", value: "php" },
  { label: "TypeScript", value: "typescript" },
  { label: "Swift", value: "swift" },
  { label: "Kotlin", value: "kotlin" },
  { label: "Perl", value: "perl" },
  { label: "R", value: "r" },
  { label: "Shell", value: "shell" },
  { label: "HTML", value: "html" },
  { label: "CSS", value: "css" },
  { label: "SQL", value: "sql" },
  { label: "JSON", value: "json" },
  { label: "XML", value: "xml" },
  { label: "YAML", value: "yaml" },
  { label: "Markdown", value: "markdown" },
  { label: "Matlab", value: "matlab" },
  { label: "Assembly", value: "assembly" },
  { label: "Dart", value: "dart" },
  { label: "Lua", value: "lua" },
  { label: "Haskell", value: "haskell" },
  { label: "Scala", value: "scala" },
  { label: "Objective-C", value: "objective-c" },
  { label: "Visual Basic", value: "vb" },
  { label: "C#", value: "csharp" },
  { label: "F#", value: "fsharp" }
];
